
## WHAT DO WE WANT - PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mongo-pvc
spec:
    storageClassName: mylocalstorage
    accessModes:
        - ReadWriteOnce
    resources:
        requests: 
            storage: 0.2Gi

---

## HOW DO WE WANT - PERSISTENT VOLUME
apiVersion: v1
kind: PersistentVolume
metadata:
    name: local-storage
spec:
    storageClassName: mylocalstorage
    capacity:
        storage: 0.2Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/mnt/some new/directory/structure"
        type: DirectoryOrCreate