kind: Service
apiVersion: v1
metadata:
    name: fleetman-webapp
spec:
    selector:
        app: webapp
    ports:
        -  name: http
           port: 80
           nodePort: 30080
    type: NodePort